server:
   port: 8764
   address: 0.0.0.0
   maxPostSize: -1
   maxHttpHeaderSize: 102400
spring:
   mvc:
      static-path-pattern: /**
   application:
      name: sg-zhixiu-eurekaserver
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   main:
      allow-bean-definition-overriding: true
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8764/eureka
      register-with-eureka: false
   server:
      enable-self-preservation: false